image: registry.gitlab.com/ea5y/ea5y-code:latest

stages:
  - test

unit-test-job:
  stage: test
  tags:
    - self-hosted
  script:
    - echo "Hello World :)"
    - echo "Installed dependencies:"
    - npm install
    - npm fund
    - npm list
    - node -v
    - chromium-browser --version
    - npm test